/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet_lieux_formations;

import Controleur.Controleur;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Epulapp
 */
public class Vue extends javax.swing.JFrame {

    protected Controleur controleur;
    
    /**
     * Creates new form Vue
     */
    public Vue() {
        controleur = new Controleur();
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelTabou = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonLancerTabou = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jButtonImporter = new javax.swing.JMenuItem();
        jButtonImporterVilles = new javax.swing.JMenuItem();
        jMenuAlgo = new javax.swing.JMenu();
        JMenuItemTabou = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 1000));

        jPanelTabou.setBorder(javax.swing.BorderFactory.createTitledBorder("Méthode Tabou"));
        jPanelTabou.setForeground(new java.awt.Color(0, 204, 204));

        jButtonLancerTabou.setText("Lancer l'algo");
        jButtonLancerTabou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLancerTabouActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jButtonLancerTabou)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jButtonLancerTabou)
                .addContainerGap(326, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelTabouLayout = new javax.swing.GroupLayout(jPanelTabou);
        jPanelTabou.setLayout(jPanelTabouLayout);
        jPanelTabouLayout.setHorizontalGroup(
            jPanelTabouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabouLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(772, Short.MAX_VALUE))
        );
        jPanelTabouLayout.setVerticalGroup(
            jPanelTabouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelTabou, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelTabou, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelTabou.setVisible(false);

        jMenu1.setText("Fichier");

        jButtonImporter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jButtonImporter.setText("Importer les agences");
        jButtonImporter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImporterActionPerformed(evt);
            }
        });
        jMenu1.add(jButtonImporter);

        jButtonImporterVilles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jButtonImporterVilles.setText("Importer les villes");
        jButtonImporterVilles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImporterVillesActionPerformed(evt);
            }
        });
        jMenu1.add(jButtonImporterVilles);

        jMenuBar1.add(jMenu1);

        jMenuAlgo.setText("Algo");

        JMenuItemTabou.setText("Méthode Tabou");
        JMenuItemTabou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemTabouActionPerformed(evt);
            }
        });
        jMenuAlgo.add(JMenuItemTabou);

        jMenuBar1.add(jMenuAlgo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonImporterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImporterActionPerformed
        // TODO add your handling code here:

        JFileChooser dialogue = new JFileChooser();

        dialogue.showOpenDialog(null);

        controleur.importerAgence(dialogue.getSelectedFile());
        
        if (controleur.getListeAgences().size() > 0 && controleur.getListeVilles().size() > 0 ) {
            jMenuAlgo.setEnabled(true);
        }
        
    }//GEN-LAST:event_jButtonImporterActionPerformed

    private void jButtonImporterVillesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImporterVillesActionPerformed
        // TODO add your handling code here:
        JFileChooser dialogue = new JFileChooser();

        dialogue.showOpenDialog(null);

        controleur.importerVille(dialogue.getSelectedFile());

        if (controleur.getListeAgences().size() > 0 && controleur.getListeVilles().size() > 0) {
            jMenuAlgo.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonImporterVillesActionPerformed

    private void JMenuItemTabouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemTabouActionPerformed
        // TODO add your handling code here:
        jPanelTabou.setVisible(true);
    }//GEN-LAST:event_JMenuItemTabouActionPerformed

    private void jButtonLancerTabouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLancerTabouActionPerformed
        // TODO add your handling code here:
        System.out.println("Taille Liste agence:" + controleur.getListeAgences().size());
        System.out.println("Taille Liste Ville:" + controleur.getListeVilles().size());
        if (controleur.getListeAgences().size() > 0 && controleur.getListeVilles().size() > 0) {
            controleur.startTabou();
        } else {
            JOptionPane jop3 = new JOptionPane();
            jop3.showMessageDialog(null, "Vous devez importer les villes et les agences avant de lancer l'algo", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonLancerTabouActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuItemTabou;
    private javax.swing.JMenuItem jButtonImporter;
    private javax.swing.JMenuItem jButtonImporterVilles;
    private javax.swing.JButton jButtonLancerTabou;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAlgo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelTabou;
    // End of variables declaration//GEN-END:variables
}
