/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet_lieux_formations;

import Controleur.Controleur;
import Modele.Agence;
import Modele.Solution;
import Modele.Ville;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Epulapp
 */
public class Vue extends javax.swing.JFrame {

    protected Controleur controleur;
    
    /**
     * Creates new form Vue
     */
    public Vue() {
        controleur = new Controleur(this);
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jBImportAgences = new javax.swing.JButton();
        jBImportVille = new javax.swing.JButton();
        jLabelNbAgences = new javax.swing.JLabel();
        jLabelNbVilles = new javax.swing.JLabel();
        jBStartTabou = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListLF = new javax.swing.JList();
        jLabelNbLF = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelCoutTotal = new javax.swing.JLabel();
        jPanelInfosLF = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelVille = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelCP = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNbAgenceForVille = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelCoutTotalForLF = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListAgenceParLF = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelNbPersonne = new javax.swing.JLabel();
        jLabelNbPlaceRestance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 1000));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Méthode Tabou", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 102, 102)));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Paramètres", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 204)));

        jBImportAgences.setText("Importer les agences");
        jBImportAgences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImportAgencesActionPerformed(evt);
            }
        });

        jBImportVille.setText("Importer les villes");
        jBImportVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImportVilleActionPerformed(evt);
            }
        });

        jBStartTabou.setText("Lancer l'agorithme");
        jBStartTabou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBStartTabouActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBImportAgences)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNbAgences, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jBStartTabou, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBImportVille, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNbVilles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBImportAgences)
                    .addComponent(jLabelNbAgences, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBImportVille)
                    .addComponent(jLabelNbVilles))
                .addGap(40, 40, 40)
                .addComponent(jBStartTabou)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jBStartTabou.setVisible(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Résultats", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 51, 204)));

        jListLF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListLFMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListLF);

        jLabelNbLF.setText("sd");

        jLabel7.setText("Coût total ");

        jLabel8.setText("Nb Lieux formation :");

        jLabelCoutTotal.setText("jLabel9");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNbLF, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCoutTotal)
                        .addGap(0, 109, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbLF)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabelCoutTotal)))
        );

        jPanelInfosLF.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 51, 204)));

        jLabel1.setText("Nom");

        jLabelVille.setText("jLabelVille");

        jLabel3.setText("Code postal");

        jLabelCP.setText("jLabel4");

        jLabel2.setText("Nombre d'agences : ");

        jLabelNbAgenceForVille.setText("jLabel4");

        jLabel4.setText("Coût pour ce lieu:");

        jLabelCoutTotalForLF.setText("jLabel5");

        jScrollPane2.setViewportView(jListAgenceParLF);

        jLabel5.setText("Nombre de personne");

        jLabel6.setText("Places restances");

        jLabelNbPersonne.setText("jLabel7");

        jLabelNbPlaceRestance.setText("jLabel7");

        javax.swing.GroupLayout jPanelInfosLFLayout = new javax.swing.GroupLayout(jPanelInfosLF);
        jPanelInfosLF.setLayout(jPanelInfosLFLayout);
        jPanelInfosLFLayout.setHorizontalGroup(
            jPanelInfosLFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfosLFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfosLFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanelInfosLFLayout.createSequentialGroup()
                        .addGroup(jPanelInfosLFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelInfosLFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVille, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCoutTotalForLF)
                            .addComponent(jLabelNbAgenceForVille, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInfosLFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInfosLFLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelInfosLFLayout.createSequentialGroup()
                                .addGroup(jPanelInfosLFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(27, 27, 27)
                                .addGroup(jPanelInfosLFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNbPlaceRestance)
                                    .addComponent(jLabelNbPersonne))
                                .addGap(0, 72, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanelInfosLFLayout.setVerticalGroup(
            jPanelInfosLFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfosLFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfosLFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelVille)
                    .addComponent(jLabel3)
                    .addComponent(jLabelCP))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfosLFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelNbAgenceForVille)
                    .addComponent(jLabel5)
                    .addComponent(jLabelNbPersonne))
                .addGroup(jPanelInfosLFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfosLFLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInfosLFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabelCoutTotalForLF)))
                    .addGroup(jPanelInfosLFLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelInfosLFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabelNbPlaceRestance))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanelInfosLF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelInfosLF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBImportAgencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImportAgencesActionPerformed
        JFileChooser dialogue = new JFileChooser();

        dialogue.showOpenDialog(null);

        controleur.importerAgence(dialogue.getSelectedFile());
        jLabelNbAgences.setText(controleur.getListeAgences().size() + " agence(s) importée(s)");
        
        if (controleur.getListeAgences().size() > 0 && controleur.getListeVilles().size() > 00) {
            jBStartTabou.setVisible(true);
        }
    }//GEN-LAST:event_jBImportAgencesActionPerformed

    private void jBImportVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImportVilleActionPerformed
        JFileChooser dialogue = new JFileChooser();

        dialogue.showOpenDialog(null);

        controleur.importerVille(dialogue.getSelectedFile());
        jLabelNbVilles.setText(controleur.getListeVilles().size() + " ville(s) importée(s)");
        
        if (controleur.getListeAgences().size() > 0 && controleur.getListeVilles().size() > 00) {
            jBStartTabou.setVisible(true);
        }
    }//GEN-LAST:event_jBImportVilleActionPerformed

    private void jBStartTabouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBStartTabouActionPerformed
        System.out.println("Taille Liste agence:" + controleur.getListeAgences().size());
        System.out.println("Taille Liste Ville:" + controleur.getListeVilles().size());
        if (controleur.getListeAgences().size() > 0 && controleur.getListeVilles().size() > 0) {
            controleur.startTabou();
        } else {
            JOptionPane jop3 = new JOptionPane();
            jop3.showMessageDialog(null, "Vous devez importer les villes et les agences avant de lancer l'algo", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBStartTabouActionPerformed

    private void jListLFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListLFMouseClicked
        jPanelInfosLF.setVisible(true);
        afficheInfosFromLF(controleur.getLieuxFormation().get(jListLF.getSelectedIndex()));
    }//GEN-LAST:event_jListLFMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vue().setVisible(true);
            }
        });
    }
    public void afficheInfos() {
         DefaultListModel list = new DefaultListModel();
         Solution solution = controleur.getSolution();
         List<Ville> listeLF = controleur.getLieuxFormation();
         int nbAgenceTotal = 0;
         double cost = 0;
        for(int i = 0; i<listeLF.size(); i++) {
            int nbAgence = listeLF.get(i).getListeAgences().size();
            nbAgenceTotal += nbAgence;
            cost += listeLF.get(i).getPriceForLF();
            list.addElement(listeLF.get(i).getNom() + " - " + listeLF.get(i).getCodePostal() + " ( " + nbAgence + " )");   
        }
        
        jListLF.setModel(list);
        jLabelNbLF.setText(nbAgenceTotal + " | " + listeLF.size());
        jLabelCoutTotal.setText(solution.getTotalPrice() + " calc: " + cost);
    }
    
    public void afficheInfosFromLF(Ville lF) {
        DefaultListModel list = new DefaultListModel();
        
        jLabelVille.setText(lF.getNom());
        jLabelCP.setText(lF.getCodePostal());
        jLabelNbAgenceForVille.setText(lF.getListeAgences().size() + "");
        jLabelNbPersonne.setText(lF.getNbPersonnePresente() + "");
        jLabelNbPlaceRestance.setText(lF.calculPlaceRestante() + "");
        jLabelCoutTotalForLF.setText(lF.getPriceForLF() + "");
       
        Solution solution = controleur.getSolution();
        List<Ville> listeLF = controleur.getLieuxFormation();
        int nbAgenceTotal = 0;
        for (int i = 0; i < lF.getListeAgences().size(); i++) {
            Agence agence = lF.getListeAgences().get(i);
            list.addElement(agence.getNom() + " - " + agence.getCodePostal() + " ( " + agence.getNbPersonne() + " personnes soit " + agence.getPriceForTransportForAgenceToLF(lF)+ " € de transport )");
        }
        jListAgenceParLF.setModel(list);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBImportAgences;
    private javax.swing.JButton jBImportVille;
    private javax.swing.JButton jBStartTabou;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCP;
    private javax.swing.JLabel jLabelCoutTotal;
    private javax.swing.JLabel jLabelCoutTotalForLF;
    private javax.swing.JLabel jLabelNbAgenceForVille;
    private javax.swing.JLabel jLabelNbAgences;
    private javax.swing.JLabel jLabelNbLF;
    private javax.swing.JLabel jLabelNbPersonne;
    private javax.swing.JLabel jLabelNbPlaceRestance;
    private javax.swing.JLabel jLabelNbVilles;
    private javax.swing.JLabel jLabelVille;
    private javax.swing.JList jListAgenceParLF;
    private javax.swing.JList jListLF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelInfosLF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
